spring.application.name=mshd
server.port=12500
spring.datasource.url=jdbc:mysql://localhost:3307/exp
spring.datasource.username=root
spring.datasource.password=REDACTED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 文件上传大小限制配置
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1000MB

# Hikari ????????
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# 数据备份配置
data.backup.time-window=365
data.backup.cron=0 0 2 * * ?
data.backup.schema=exp_backup

